# Numpy and Pandas

## Numpy

In [1]:
import numpy as np

In [2]:
d = np.zeros(5)
d

array([0., 0., 0., 0., 0.])

In [3]:
type(d[0])

numpy.float64

In [4]:
d = np.ones(5, dtype = int)
d

array([1, 1, 1, 1, 1])

In [5]:
d = np.array(list(range(5)))
d

array([0, 1, 2, 3, 4])

In [6]:
d = np.linspace(1,100,11,dtype = int)
d

array([  1,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### more dimensions

In [7]:
d2 = np.ones([3,5],dtype = int)
d2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
d2 = np.array([[1,2,3],
               [4,5,6]])
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
d2.shape

(2, 3)

In [10]:
d2 = np.random.rand(3,2,4)
d2

array([[[0.82248288, 0.26244657, 0.12084544, 0.19212554],
        [0.09367085, 0.45331647, 0.74921953, 0.19526415]],

       [[0.65435251, 0.3324739 , 0.24558362, 0.53671312],
        [0.04007779, 0.18058552, 0.98565988, 0.12664314]],

       [[0.45201175, 0.42021205, 0.06740981, 0.9460648 ],
        [0.76861917, 0.34457805, 0.95720002, 0.40913446]]])

In [11]:
d2 = np.random.randint(20,50,size = 7)
d2

array([39, 20, 46, 44, 34, 42, 26])

In [12]:
d2 = np.random.random(10)
d2

array([0.98936851, 0.04335668, 0.97242949, 0.80654091, 0.94958191,
       0.12341014, 0.57175781, 0.8718546 , 0.13492157, 0.85416896])

In [13]:
d2 = np.random.choice(100,3)
d2

array([ 3, 40, 37])

## Pandas

In [14]:
import pandas as pd

###  Ontario COVID-19 outbreaks data

https://data.ontario.ca/dataset/ontario-covid-19-outbreaks-data

This dataset compiles daily snapshots of publicly reported data on 2019 Novel Coronavirus (COVID-19) outbreaks in Ontario.

Data includes:
- Summary of cases associated with outbreaks, by outbreak setting and date
- Summary of ongoing outbreaks by outbreak setting

This dataset is subject to change. 

In [15]:
df = pd.read_csv("https://data.ontario.ca/dataset/5472ffc1-88e2-48ca-bc9f-4aa249c1298d/resource/d5d8f478-765c-4246-b8a7-c3b13a4a1a41/download/outbreak_cases.csv")
df.head(10)

date     category_grouped              outbreak_subgroup  TOTAL_CASES
0  2020-03-06  2 Congregate Living                        SHELTER            1
1  2020-03-08    1 Congregate Care            LONG-TERM CARE HOME            1
2  2020-03-09          4 Workplace              WORKPLACE - OTHER            1
3  2020-03-11  2 Congregate Living  GROUP HOME/SUPPORTIVE HOUSING            1
4  2020-03-12    1 Congregate Care            LONG-TERM CARE HOME            1
5  2020-03-13    1 Congregate Care            LONG-TERM CARE HOME            1
6  2020-03-14          4 Workplace              WORKPLACE - OTHER            1
7  2020-03-15          4 Workplace              WORKPLACE - OTHER            1
8  2020-03-17    1 Congregate Care            LONG-TERM CARE HOME            2
9  2020-03-18          4 Workplace              WORKPLACE - OTHER            2

In [16]:
df.shape

(2759, 4)

In [19]:
df.groupby(['outbreak_subgroup']).sum()

TOTAL_CASES
outbreak_subgroup                         
BAR/RESTAURANT/NIGHTCLUB               423
CHILD CARE                             411
CONGREGATE OTHER                       364
CORRECTIONAL FACILITY                  202
GROUP HOME/SUPPORTIVE HOUSING         1190
HOSPITAL                              2107
LONG-TERM CARE HOME                  14804
MEDICAL/HEALTH SERVICE                 168
OTHER                                  174
OTHER RECREATION                       557
PERSONAL SERVICE SETTINGS               36
RECREATIONAL FITNESS                   388
RETAIL                                 349
RETIREMENT HOME                       3388
SCHOOL - ELEMENTARY                   1109
SCHOOL - ELEMENTARY/SECONDARY          161
SCHOOL - POST-SECONDARY                 34
SCHOOL - SECONDARY                     357
SHELTER                                653
SHORT-TERM ACCOMMODATIONS               14
UNKNOWN                                 65
WORKPLACE - FARM                      1561
WORKPLACE - FOOD PROCESSING            979
WORKPLACE - OTHER                     3154

In [21]:
dayct = df[['date','TOTAL_CASES']].groupby(['date']).sum()

In [26]:
dayct.plot(figsize = (10,7))

<AxesSubplot:xlabel='date'>